<?php

namespace CMS\Core\Component\Sitemaps\Collections;

use CMS\Core\Component\Sitemaps\Controls\BaseSitemaps;
use Delorius\Core\Environment;


class CommonSitemaps extends BaseSitemaps
{
    /**
     * site
     * name
     * domain
     */

    public function initUrls()
    {
    }

    public function addUrl($loc, $lastmod = null, $changefreq = null, $priority = 0.5)
    {
        parent::addUrl($loc, $lastmod, $changefreq, $priority);
    }

    public function createXML()
    {
        return parent::createXML(); // TODO: Change the autogenerated stub
    }

    public function location()
    {
        $domainRouter = Environment::getContext()
            ->getService('domainRouter');
        $host = $domainRouter->generate($this->options['domain']);
        return $host . $this->getPath(false);
    }


}